kind = "DojoModel"
class_hash = "0xf00737ffe57c5c931bfec9a7ea66f76d5eaae12cacca6952dcee0c2e3d8038"
original_class_hash = "0xf00737ffe57c5c931bfec9a7ea66f76d5eaae12cacca6952dcee0c2e3d8038"
abi = "manifests/dev/abis/base/models/dojo_starter_systems_actions_actions_moved.json"
name = "dojo_starter::systems::actions::actions::moved"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "direction"
type = "Direction"
key = false
